### ISSUE TITLE
城里人真会玩

### ISSUE THREAD

**Issue by hr567** [NdefStudio/TRPGBackgroundSet-Record#3]
哈哈哈，我仿佛看到了 Github 的错误打开方式。
你们可以合作直接开发一个联机跑团游戏呢（微笑）。

**Comment by NdefStudio** [comment]
哇捕捉野生的hr567
没怎么用过github又发现新建世界观的任务很适合用git组织
（就这样开始学了顺便带人入坑hhh

~~10年时间一定能做出来大卖
走上人生巅峰~~
