### ISSUE TITLE
Creating framework for character-sheets

### ISSUE THREAD

**Issue by NdefStudio** [NdefStudio/TRPGBackgroundSet-Record#7]
目前打算用excel做一个可以**自动加点** ~~roll点~~ ，根据**职业等级**和**技能熟练点**算好所有**技能加值**，自动显示职业**战术动作**的角色卡模板。
不知道有没有什么别的工具可以实现，我只会excel）

**Comment by hr567** [comment]
excel 可还行……
考虑到易用程度和可移植性，写个网页比较好吧（应该不太复杂吧

**Comment by NdefStudio** [comment]
网页……好主意，卡上信息的存储怎么解决比较好（xml？  
~~（学到的东西从来没有实操过~~

**Comment by hr567** [comment]
json 吧，多省事啊

**Comment by NdefStudio** [comment]
ok，我试试（
